#requires -Version 5.1
<#
.SYNOPSIS
Installs an exact CPython version and makes it the Windows command default.
.EXAMPLE
powershell -NoProfile -ExecutionPolicy Bypass -File .\setup-python-windows.ps1
.EXAMPLE
.\setup-python-windows.ps1 -Version 3.11.1
.EXAMPLE
.\setup-python-windows.ps1 -Version 3.11.1 -Isolated -InstallRoot C:\Temp\PythonTest
.NOTES
Normal mode requests UAC elevation and uses Program Files and machine PATH.
Isolated mode never modifies persistent PATH, profiles, or the registry.
Dot-source this file to load its functions without running the installer.
#>
[CmdletBinding()]
param([string]$Version, [switch]$Yes, [switch]$Isolated, [string]$InstallRoot, [switch]$NoElevate,
      [Parameter(DontShow)][string]$ExpectedUserSid)

function Assert-PythonVersion([string]$Value) {
    if ($Value -notmatch '^3\.([1-9][0-9]?)\.(0|[1-9][0-9]{0,2})$' -or [int]$Matches[1] -lt 8) {
        throw 'Use an exact stable CPython version, such as 3.11.1 (3.8+).'
    }
}
function Get-UvPlatform([string]$Architecture) {
    switch ($Architecture.ToUpperInvariant()) {
        'AMD64' { 'x86_64' }
        'ARM64' { 'aarch64' }
        'X86' { 'i686' }
        default { throw "Unsupported Windows architecture: $Architecture" }
    }
}
function Assert-DownloadHash([string]$Path, [string]$Expected) {
    if ((Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash -ne $Expected) {
        throw "Download checksum mismatch: $Path"
    }
}
function Get-SelectedPath([string]$Bin, [string]$Original, [string[]]$Remove = @()) {
    $excluded = @($Bin) + $Remove | ForEach-Object { $_.TrimEnd('\','/').ToLowerInvariant() }
    $entries = @($Bin)
    foreach ($item in ($Original -split ';')) {
        if ($item -and $item.TrimEnd('\','/').ToLowerInvariant() -notin $excluded) { $entries += $item }
    }
    $entries -join ';'
}
function Get-ActivationText([string]$Bin) {
    $literal = "'" + $Bin.Replace("'", "''") + "'"
    @'
# Generated by PythonSelector. Dot-source to activate in an existing terminal.
foreach ($pythonSelectorName in @('python','python3','pip','pip3')) {
    Remove-Item "Alias:$pythonSelectorName" -Force -ErrorAction SilentlyContinue
    Remove-Item "Function:$pythonSelectorName" -Force -ErrorAction SilentlyContinue
}
foreach ($pythonSelectorName in @('PYTHONHOME','PYTHONPATH','PYTHONSTARTUP','PYTHONUSERBASE','VIRTUAL_ENV','__PYVENV_LAUNCHER__')) {
    [Environment]::SetEnvironmentVariable($pythonSelectorName,$null,'Process')
}
'@ + "`r`n`$pythonSelectorBin = $literal`r`n" + @'
$pythonSelectorScripts = Join-Path $pythonSelectorBin 'Scripts'
$pythonSelectorEntries = @($env:PATH -split ';' | Where-Object {
    $_ -and $_.TrimEnd('\','/') -ine $pythonSelectorBin.TrimEnd('\','/') -and
    $_.TrimEnd('\','/') -ine $pythonSelectorScripts.TrimEnd('\','/')
})
$env:PATH = (@($pythonSelectorBin,$pythonSelectorScripts) + $pythonSelectorEntries) -join ';'
Remove-Variable pythonSelectorName,pythonSelectorBin,pythonSelectorScripts,pythonSelectorEntries -ErrorAction SilentlyContinue
'@
}
function Set-ManagedProfile([string]$Path, [string]$Block) {
    $text = ''
    $encoding = [Text.UTF8Encoding]::new($true)
    if (Test-Path -LiteralPath $Path) {
        $reader = [IO.StreamReader]::new($Path, [Text.UTF8Encoding]::new($false,$true), $true)
        try { $text = $reader.ReadToEnd(); $encoding = $reader.CurrentEncoding }
        catch { throw "Cannot safely decode profile $Path. Save it as UTF-8 with BOM or UTF-16, then rerun. No profile bytes were changed." }
        finally { $reader.Dispose() }
        # PowerShell 5.1 treats BOM-less non-ASCII as ANSI. Emit a UTF-8 BOM
        # when the original was UTF-8, including previously ASCII-only files.
        if ($encoding.CodePage -eq 65001) { $encoding = [Text.UTF8Encoding]::new($true) }
    }
    $inside = $false
    foreach ($line in ($text -split '\r?\n')) {
        if ($line -eq '# >>> PythonSelector >>>') {
            if ($inside) { throw "Malformed PythonSelector block in $Path" }
            $inside = $true
        }
        if ($line -eq '# <<< PythonSelector <<<') {
            if (-not $inside) { throw "Malformed PythonSelector block in $Path" }
            $inside = $false
        }
    }
    if ($inside) { throw "Malformed PythonSelector block in $Path" }
    $text = [regex]::Replace($text, '(?ms)^# >>> PythonSelector >>>\r?\n.*?^# <<< PythonSelector <<<\r?(?:\n|\z)', '')
    $text = $text.TrimEnd("`r","`n") + "`r`n`r`n# >>> PythonSelector >>>`r`n" + $Block + "`r`n# <<< PythonSelector <<<`r`n"
    [void][IO.Directory]::CreateDirectory((Split-Path -Parent $Path))
    [IO.File]::WriteAllText($Path,$text,$encoding)
}
function Invoke-CleanEnvironment([scriptblock]$Body) {
    $saved = @{}
    foreach ($item in @(Get-ChildItem Env:)) {
        if ($item.Name -match '^(UV_|PYTHON)' -or $item.Name -in @('VIRTUAL_ENV','CONDA_PREFIX','CONDA_DEFAULT_ENV','__PYVENV_LAUNCHER__')) {
            $saved[$item.Name] = $item.Value
            [Environment]::SetEnvironmentVariable($item.Name,$null,'Process')
        }
    }
    try { & $Body } finally {
        foreach ($item in @(Get-ChildItem Env:)) {
            if ($item.Name -match '^(UV_|PYTHON)' -or $item.Name -in @('VIRTUAL_ENV','CONDA_PREFIX','CONDA_DEFAULT_ENV','__PYVENV_LAUNCHER__')) {
                [Environment]::SetEnvironmentVariable($item.Name,$null,'Process')
            }
        }
        foreach ($key in $saved.Keys) { [Environment]::SetEnvironmentVariable($key,$saved[$key],'Process') }
    }
}
function Invoke-Uv([string]$Executable, [string]$Root, [string[]]$Arguments) {
    Invoke-CleanEnvironment {
        $env:UV_PYTHON_INSTALL_DIR = Join-Path $Root 'runtimes'
        $env:UV_CACHE_DIR = Join-Path $Root 'cache'
        $env:UV_NO_PROGRESS = '1'
        & $Executable --no-config --system-certs @Arguments
        if ($LASTEXITCODE -ne 0) { throw "uv failed (exit $LASTEXITCODE): $($Arguments -join ' ')" }
    }
}
function Get-VerifiedUv([string]$Root, [string]$Stage, [string]$Architecture) {
    $uv = Join-Path $Root 'tools\uv-0.12.19.exe'
    if (Test-Path -LiteralPath $uv) {
        $installedVersion = & $uv --version
        if ($LASTEXITCODE -eq 0 -and $installedVersion -like 'uv 0.12.19*') { return $uv }
    }
    $hashes = @{
        x86_64 = '6dbb02d79e419522f1c500f0adb1cddcff0cda7d59b0d66ea7f5e3b4a1b2f5f0'
        aarch64 = '115b54cb823bc48260670f5782001add6067ac8d98d18c8263a833704e287de9'
        i686 = 'e1c2d19d1173a0e9f81ba3f95881ad741808133e372610889ff6870629218c7f'
    }
    $asset = "uv-$Architecture-pc-windows-msvc.zip"
    $archive = Join-Path $Stage $asset
    $uri = "https://github.com/astral-sh/uv/releases/download/0.12.19/$asset"
    Write-Host "Downloading verified uv 0.12.19 ($Architecture)..."
    $tls = [Net.ServicePointManager]::SecurityProtocol
    try {
        [Net.ServicePointManager]::SecurityProtocol = $tls -bor [Net.SecurityProtocolType]::Tls12
        for ($attempt = 1; $attempt -le 3; $attempt++) {
            try { Invoke-WebRequest -UseBasicParsing -Uri $uri -OutFile $archive -TimeoutSec 600; break }
            catch { if ($attempt -eq 3) { throw }; Start-Sleep -Seconds $attempt }
        }
    } finally { [Net.ServicePointManager]::SecurityProtocol = $tls }
    Assert-DownloadHash $archive $hashes[$Architecture]
    $extract = Join-Path $Stage 'uv-extract'
    Expand-Archive -LiteralPath $archive -DestinationPath $extract
    $binary = @(Get-ChildItem -LiteralPath $extract -Filter uv.exe -Recurse)
    if ($binary.Count -ne 1) { throw 'Unexpected uv archive layout' }
    [void][IO.Directory]::CreateDirectory((Split-Path -Parent $uv))
    Copy-Item -LiteralPath $binary[0].FullName -Destination $uv -Force
    Remove-Item -LiteralPath $archive -Force
    return $uv
}
function Save-ConfigFile([string]$Path, [string]$Backup, [int]$Index) {
    $exists = Test-Path -LiteralPath $Path
    $copy = Join-Path $Backup "$Index"
    if ($exists) { Copy-Item -LiteralPath $Path -Destination $copy -Force }
    [pscustomobject]@{ Path=$Path; Existed=$exists; Backup=$copy }
}
function Restore-ConfigFiles([object[]]$Items) {
    for ($index = $Items.Count - 1; $index -ge 0; $index--) {
        $item = $Items[$index]
        if ($item.Existed) { [IO.File]::WriteAllBytes($item.Path,[IO.File]::ReadAllBytes($item.Backup)) }
        elseif (Test-Path -LiteralPath $item.Path) { Remove-Item -LiteralPath $item.Path -Force }
    }
}
function Get-EnvironmentEntry([string]$Name, [string]$Scope) {
    $baseKey = [Microsoft.Win32.Registry]::CurrentUser
    $subkey = 'Environment'
    if ($Scope -eq 'Machine') {
        $baseKey = [Microsoft.Win32.Registry]::LocalMachine
        $subkey = 'SYSTEM\CurrentControlSet\Control\Session Manager\Environment'
    }
    $key = $baseKey.OpenSubKey($subkey)
    try {
        $exists = $null -ne $key -and $Name -in $key.GetValueNames()
        $value = $null
        $kind = 'ExpandString'
        if ($exists) {
            $value = $key.GetValue($Name,$null,[Microsoft.Win32.RegistryValueOptions]::DoNotExpandEnvironmentNames)
            $kind = $key.GetValueKind($Name).ToString()
        }
        [pscustomobject]@{Name=$Name;Scope=$Scope;Value=$value;Kind=$kind;Existed=$exists}
    } finally { if ($key) { $key.Dispose() } }
}
function Set-EnvironmentEntry($Entry) {
    $baseKey = [Microsoft.Win32.Registry]::CurrentUser
    $subkey = 'Environment'
    if ($Entry.Scope -eq 'Machine') {
        $baseKey = [Microsoft.Win32.Registry]::LocalMachine
        $subkey = 'SYSTEM\CurrentControlSet\Control\Session Manager\Environment'
    }
    $key = $baseKey.CreateSubKey($subkey)
    try {
        if (-not $Entry.Existed) { $key.DeleteValue($Entry.Name,$false) }
        else { $key.SetValue($Entry.Name,$Entry.Value,[Microsoft.Win32.RegistryValueKind]$Entry.Kind) }
    } finally { $key.Dispose() }
}
function Save-RecoveryManifest([string]$Backup, $Files, $Environment) {
    [IO.File]::WriteAllText((Join-Path $Backup 'files.json'),(ConvertTo-Json -InputObject @($Files.ToArray()) -Depth 5))
    [IO.File]::WriteAllText((Join-Path $Backup 'environment.json'),(ConvertTo-Json -InputObject @($Environment.ToArray()) -Depth 5))
}
function Invoke-CheckedPython([string]$Python, [string[]]$Arguments) {
    $PSNativeCommandUseErrorActionPreference = $false
    & $Python @Arguments
    if ($LASTEXITCODE -ne 0) { throw "Python check failed (exit $LASTEXITCODE): $($Arguments -join ' ')" }
}
function Get-HealthyPython([string]$Uv, [string]$Root, [string]$Request, [string]$Wanted, [string]$Stage) {
    Invoke-CleanEnvironment {
        for ($attempt=0; $attempt -lt 2; $attempt++) {
            try {
                $python = ((Invoke-Uv $Uv $Root @('python','find',$Request,'--system','--managed-python','--no-project','--no-python-downloads','--resolve-links')) -join '').Trim()
                $actual = Invoke-CheckedPython $python @('-I','-c','import platform, ssl, sqlite3, venv; print(platform.python_version())')
                if ($actual -ne $Wanted) { throw "Requested $Wanted, executed $actual." }
                # Expected native stderr must not become a terminating error on
                # Windows PowerShell 5.1 before we can inspect the exit status.
                $pipExit = & {
                    $ErrorActionPreference = 'Continue'
                    $PSNativeCommandUseErrorActionPreference = $false
                    & $python -I -m pip --version 2>$null | Out-Null
                    $LASTEXITCODE
                }
                if ($pipExit -ne 0) { Invoke-CheckedPython $python @('-I','-m','ensurepip','--upgrade','--default-pip') | Out-Host }
                Invoke-CheckedPython $python @('-I','-m','pip','--version') | Out-Host
                $venv = Join-Path $Stage 'venv-check'
                if (Test-Path -LiteralPath $venv) { Remove-Item -LiteralPath $venv -Recurse -Force }
                Invoke-CheckedPython $python @('-I','-m','venv',$venv) | Out-Host
                $venvVersion = Invoke-CheckedPython (Join-Path $venv 'Scripts\python.exe') @('-I','-c','import platform; print(platform.python_version())')
                if ($venvVersion -ne $Wanted) { throw 'Virtual environment uses the wrong Python version.' }
                Remove-Item -LiteralPath $venv -Recurse -Force
                return $python
            } catch {
                if ($attempt -eq 1) { throw }
                Write-Host 'Managed runtime failed complete verification; repairing it once...'
                Invoke-Uv $Uv $Root @('python','install',$Request,'--no-bin','--no-registry','--reinstall') | Out-Host
            }
        }
    }
}
function Send-EnvironmentNotification {
    if (-not ('PythonSelector.NativeMethods' -as [type])) {
        Add-Type @'
using System;
using System.Runtime.InteropServices;
namespace PythonSelector {
    public class NativeMethods {
        [DllImport("user32.dll", CharSet=CharSet.Unicode, SetLastError=true)]
        public static extern IntPtr SendMessageTimeout(IntPtr window, uint message,
            UIntPtr wParam, string lParam, uint flags, uint timeout, out UIntPtr result);
    }
}
'@
    }
    $result = [UIntPtr]::Zero
    [void][PythonSelector.NativeMethods]::SendMessageTimeout([IntPtr]0xffff,0x1a,[UIntPtr]::Zero,'Environment',2,5000,[ref]$result)
}

function Invoke-PythonSetup {
    $ErrorActionPreference = 'Stop'
    Set-StrictMode -Version Latest
    if ([Environment]::OSVersion.Platform -ne [PlatformID]::Win32NT) { throw 'This installer requires Windows.' }
    if ([Environment]::OSVersion.Version.Major -lt 10) { throw 'Windows 10 or later is required.' }
    if (-not $Version) {
        if ($Yes) { $Version = '3.11.1' }
        else { $Version = Read-Host 'Exact Python version to install [3.11.1]'; if (-not $Version) { $Version = '3.11.1' } }
    }
    Assert-PythonVersion $Version
    if ($Isolated -and -not $InstallRoot) { throw '-Isolated requires -InstallRoot.' }
    if (-not $Isolated -and $InstallRoot) { throw '-InstallRoot is allowed only with -Isolated; normal installation uses protected Program Files.' }
    if (-not $Isolated) {
        $identity = [Security.Principal.WindowsIdentity]::GetCurrent()
        if ($ExpectedUserSid -and $ExpectedUserSid -ne $identity.User.Value) {
            throw 'UAC switched to a different account. Run using an administrator account with its own session; the original user was not configured.'
        }
        $admin = ([Security.Principal.WindowsPrincipal]::new($identity)).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
        if (-not $admin) {
            if ($NoElevate) { throw 'Administrator permission is required to override machine PATH. Run PowerShell as administrator.' }
            Write-Host 'Administrator permission is required to set machine PATH. Requesting UAC elevation...'
            $scriptPath = $PSCommandPath
            if (-not $scriptPath -or $scriptPath.Contains('"')) { throw 'Save this script as a .ps1 file before running it.' }
            $arguments = '-NoLogo -NoProfile -ExecutionPolicy Bypass -File "' + $scriptPath + '" -Version ' + $Version + ' -NoElevate -ExpectedUserSid ' + $identity.User.Value
            $hostExe = Join-Path $env:SystemRoot 'System32\WindowsPowerShell\v1.0\powershell.exe'
            $process = Start-Process -FilePath $hostExe -ArgumentList $arguments -Verb RunAs -Wait -PassThru
            if ($process.ExitCode -ne 0) { throw "Elevated installer failed with exit code $($process.ExitCode)." }
            return
        }
        $programFiles = [Environment]::GetEnvironmentVariable('ProgramW6432')
        if (-not $programFiles) { $programFiles = $env:ProgramFiles }
        $InstallRoot = Join-Path $programFiles 'PythonSelector'
    }
    if (-not [IO.Path]::IsPathRooted($InstallRoot) -or $InstallRoot -match '[%\r\n;]' -or $InstallRoot.StartsWith('\\')) {
        throw 'InstallRoot must be an absolute local path without percent signs, semicolons or newlines.'
    }
    $root = [IO.Path]::GetFullPath($InstallRoot).TrimEnd('\','/')
    if ($root -eq [IO.Path]::GetPathRoot($root).TrimEnd('\','/')) { throw 'InstallRoot cannot be a drive root.' }
    [void][IO.Directory]::CreateDirectory($root)
    if ((Get-Item -LiteralPath $root).Attributes -band [IO.FileAttributes]::ReparsePoint) { throw 'InstallRoot cannot be a junction or symbolic link.' }
    try { $lock = [IO.File]::Open((Join-Path $root '.lock'),[IO.FileMode]::OpenOrCreate,[IO.FileAccess]::ReadWrite,[IO.FileShare]::None) }
    catch { throw "Another installer owns $root\.lock, or the directory is not writable." }
    $stage = Join-Path $root ('run.' + [guid]::NewGuid().ToString('N'))
    $backup = Join-Path $stage 'backup'
    [void][IO.Directory]::CreateDirectory($backup)
    $savedFiles = [Collections.Generic.List[object]]::new()
    $savedEnvironment = [Collections.Generic.List[object]]::new()
    $transaction = $false
    $oldProcessPath = $env:PATH
    $activate = Join-Path $root 'activate.ps1'
    $selectionFile = Join-Path $root 'selection.json'
    try {
        $architecture = $env:PROCESSOR_ARCHITEW6432
        if (-not $architecture) { $architecture = $env:PROCESSOR_ARCHITECTURE }
        $uvPlatform = Get-UvPlatform $architecture
        $uv = Get-VerifiedUv $root $stage $uvPlatform
        $pythonArch = $uvPlatform
        if ($pythonArch -eq 'i686') { $pythonArch = 'x86' }
        $available = @((Invoke-Uv $uv $root @('python','list',$Version,'--all-versions','--all-arches','--only-downloads','--output-format','json')) -join "`n" | ConvertFrom-Json)
        $availableKeys = @($available | ForEach-Object { $_.key })
        $request = "cpython-$Version-windows-$pythonArch-none"
        if ($request -notin $availableKeys) {
            if ($pythonArch -eq 'aarch64' -and "cpython-$Version-windows-x86_64-none" -in $availableKeys) {
                $request = "cpython-$Version-windows-x86_64-none"
                Write-Host "Python $Version has no native ARM64 build in this catalog; using x64 (requires Windows x64 emulation)."
            } else { throw "No exact $Version build is available for $architecture in uv 0.12.19. No defaults were changed." }
        }
        Write-Host "Installing/selecting $request..."
        Invoke-Uv $uv $root @('python','install',$request,'--no-bin','--no-registry')
        $python = Get-HealthyPython $uv $root $request $Version $stage
        $bin = Split-Path -Parent $python
        # All executable aliases stay beside their DLLs and stdlib. Avoid the
        # movable minor-version links that could silently change patch versions.
        Copy-Item -LiteralPath $python -Destination (Join-Path $bin 'python3.exe') -Force
        foreach ($name in @('pip','pip3')) {
            [IO.File]::WriteAllText((Join-Path $bin "$name.cmd"), "@echo off`r`n`"%~dp0python.exe`" -m pip %*`r`n", [Text.Encoding]::ASCII)
        }
        $previousBins = @()
        if (Test-Path -LiteralPath $selectionFile) {
            $previous = Get-Content -LiteralPath $selectionFile -Raw | ConvertFrom-Json
            $previousBins = @($previous.bin, (Join-Path $previous.bin 'Scripts'))
        }
        $transaction = $true
        foreach ($path in @($activate,$selectionFile)) { $savedFiles.Add((Save-ConfigFile $path $backup $savedFiles.Count)) }
        Save-RecoveryManifest $backup $savedFiles $savedEnvironment
        [IO.File]::WriteAllText($activate,(Get-ActivationText $bin),[Text.UTF8Encoding]::new($true))
        [IO.File]::WriteAllText($selectionFile,(@{version=$Version;bin=$bin;python=$python;architecture=$request} | ConvertTo-Json),[Text.UTF8Encoding]::new($false))
        if (-not $Isolated) {
            foreach ($scope in @('Machine','User')) {
                foreach ($name in @('Path','PYTHONHOME','PYTHONPATH','PYTHONSTARTUP','PYTHONUSERBASE')) {
                    $entry = Get-EnvironmentEntry $name $scope
                    $savedEnvironment.Add($entry)
                    Save-RecoveryManifest $backup $savedFiles $savedEnvironment
                    if ($name -eq 'Path') {
                        $newPath = Get-SelectedPath (Join-Path $bin 'Scripts') $entry.Value $previousBins
                        $newPath = Get-SelectedPath $bin $newPath
                        Set-EnvironmentEntry ([pscustomobject]@{Name=$name;Scope=$scope;Value=$newPath;Kind=$entry.Kind;Existed=$true})
                    } else { Set-EnvironmentEntry ([pscustomobject]@{Name=$name;Scope=$scope;Existed=$false}) }
                }
            }
            $documents = [Environment]::GetFolderPath('MyDocuments')
            $profiles = @($PROFILE.CurrentUserAllHosts, $PROFILE.CurrentUserCurrentHost)
            foreach ($folder in @('WindowsPowerShell','PowerShell')) {
                foreach ($file in @('profile.ps1','Microsoft.PowerShell_profile.ps1','Microsoft.VSCode_profile.ps1','Microsoft.PowerShellISE_profile.ps1')) {
                    $profiles += Join-Path (Join-Path $documents $folder) $file
                }
            }
            $block = ". '" + $activate.Replace("'","''") + "'"
            foreach ($path in @($profiles | Select-Object -Unique)) {
                $savedFiles.Add((Save-ConfigFile $path $backup $savedFiles.Count))
                Save-RecoveryManifest $backup $savedFiles $savedEnvironment
                Set-ManagedProfile $path $block
            }
            Send-EnvironmentNotification
        }
        # Keep durable backups even if a later check rolls back the changes.
        Save-RecoveryManifest $backup $savedFiles $savedEnvironment
        . $activate
        foreach ($name in @('python','python3')) {
            $command = Get-Command $name -CommandType Application | Select-Object -First 1
            $actual = Invoke-CheckedPython $command.Source @('-c','import platform; print(platform.python_version())')
            if ($actual -ne $Version) { throw "$name executes $actual, expected $Version." }
            Write-Host "$name -> $($command.Source) ($actual)"
        }
        foreach ($name in @('pip','pip3')) {
            & $name --version
            if ($LASTEXITCODE -ne 0) { throw "$name verification failed." }
        }
        $transaction = $false
        Write-Host "`nVerified Python $Version. Activation: $activate"
        Write-Host "Backups: $backup"
        if ($Isolated) { Write-Host 'Isolated mode: persistent PATH and profiles were not changed.' }
        else { Write-Host 'Close and reopen terminals and IDEs. Windows Terminal may need a full restart or sign-out to refresh PATH.' }
    } catch {
        if ($transaction) {
            Write-Warning 'Configuration failed; restoring the previous default and profiles.'
            try { Restore-ConfigFiles $savedFiles.ToArray() } catch { Write-Warning "FILE RESTORE FAILED: $_" }
            foreach ($item in $savedEnvironment) {
                try { Set-EnvironmentEntry $item }
                catch { Write-Warning "ENVIRONMENT RESTORE FAILED: $($item.Name) $($item.Scope): $_" }
            }
            $env:PATH = $oldProcessPath
            if (-not $Isolated) { try { Send-EnvironmentNotification } catch { Write-Warning "Environment notification failed: $_" } }
            Write-Warning "Recovery files: $backup"
        }
        throw
    } finally { $lock.Dispose() }
}

if ($MyInvocation.InvocationName -ne '.') {
    try { Invoke-PythonSetup } catch { Write-Error $_ -ErrorAction Continue; exit 1 }
}
