#!/bin/bash
# Exact CPython selection. Works with the Bash 3.2 supplied by macOS.
# Usage: bash setup-python-mac.sh [--version 3.11.1] [--yes]+# Tests: --isolated --root /absolute/temporary/directory (no profile changes).

fail() { printf 'ERROR: %s\n' "$*" >&2; return 1; }
validate_version() {
    [[ "$1" =~ ^3\.([1-9][0-9]?)\.(0|[1-9][0-9]{0,2})$ ]] &&
        (( ${BASH_REMATCH[1]} >= 8 )) ||
        { fail 'Use an exact stable CPython version, such as 3.11.1 (3.8+).'; return 1; }
}
verify_sha256() {
    local actual
    actual=$(/usr/bin/shasum -a 256 "$1") || return 1
    [[ "${actual%% *}" == "$2" ]] || { fail "Download checksum mismatch: $1"; return 1; }
}

# Refuse malformed blocks rather than accidentally deleting unrelated settings.
# Write through symlinks to preserve dotfile-manager links.
write_profile() {
    local target="$1" block="$2" temp
    temp=$(/usr/bin/mktemp) || return 1
    if [[ -e "$target" ]]; then
        if ! /usr/bin/awk '
            $0 == "# >>> PythonSelector >>>" { if (inside) exit 41; inside=1; next }
            $0 == "# <<< PythonSelector <<<" { if (!inside) exit 42; inside=0; next }
            !inside { print }
            END { if (inside) exit 43 }
        ' "$target" > "$temp"; then
            /bin/rm -f "$temp"
            fail "Malformed PythonSelector block in $target; restore or repair it first."
            return 1
        fi
    fi
    { printf '\n# >>> PythonSelector >>>\n'; /bin/cat "$block"; printf '\n# <<< PythonSelector <<<\n'; } >> "$temp"
    /bin/mkdir -p "$(/usr/bin/dirname "$target")" || { /bin/rm -f "$temp"; return 1; }
    /bin/cat "$temp" > "$target" || { /bin/rm -f "$temp"; return 1; }
    /bin/rm -f "$temp"
}

make_activation() {
    local quoted
    printf -v quoted '%q' "$1/current/bin"
    {
        printf '# Generated by PythonSelector; source this file in Bash or Zsh.\n'
        printf '_python_selector_bin=%s\n' "$quoted"
        /bin/cat <<'SHELL'
# Remove only command names managed by this installer.
for _python_selector_name in python python3 pip pip3; do
    unalias "$_python_selector_name" 2>/dev/null || :
    unset -f "$_python_selector_name" 2>/dev/null || :
done
unset PYTHONHOME PYTHONPATH PYTHONSTARTUP PYTHONUSERBASE __PYVENV_LAUNCHER__ VIRTUAL_ENV
# Remove previous copies of our PATH entry without changing other entries.
_python_selector_rest=${PATH-}
_python_selector_path=
while :; do
    _python_selector_part=${_python_selector_rest%%:*}
    if [ "$_python_selector_part" != "$_python_selector_bin" ]; then
        _python_selector_path="$_python_selector_path:$_python_selector_part"
    fi
    case $_python_selector_rest in
        *:*) _python_selector_rest=${_python_selector_rest#*:} ;;
        *) break ;;
    esac
done
export PATH="$_python_selector_bin$_python_selector_path"
hash -r 2>/dev/null || :
unset _python_selector_bin _python_selector_name _python_selector_rest
unset _python_selector_path _python_selector_part
SHELL
    } > "$2"
}

download_uv() {
    local arch="$1" asset expected archive extracted
    case "$arch" in
        aarch64) expected=a9a8df1eedeb192f2e47e40e2faabfb387db4b850209118786d42f89dde3e0ba ;;
        x86_64) expected=cb5fa57bafe68fc0fb94b17f06bee0b0b9a7feb94ccbd110445afa0696e39273 ;;
        *) fail "Unsupported architecture: $arch"; return 1 ;;
    esac
    uv="$root/tools/uv-0.12.19"
    if [[ -x "$uv" ]] && [[ "$("$uv" --version)" == 'uv 0.12.19'* ]]; then return; fi
    asset="uv-$arch-apple-darwin.tar.gz"
    archive="$generation/$asset"
    printf 'Downloading verified uv 0.12.19 (%s)...\n' "$arch"
    /usr/bin/curl --fail --location --silent --show-error --proto '=https' --proto-redir '=https' \
        --tlsv1.2 --retry 3 --connect-timeout 20 --max-time 600 \
        "https://github.com/astral-sh/uv/releases/download/0.12.19/$asset" -o "$archive"
    verify_sha256 "$archive" "$expected"
    /usr/bin/tar -xzf "$archive" -C "$generation"
    extracted="$generation/uv-$arch-apple-darwin/uv"
    /bin/mkdir -p "$root/tools"
    /bin/cp "$extracted" "$uv.tmp"
    /bin/chmod 755 "$uv.tmp"
    /bin/mv -f "$uv.tmp" "$uv"
    /bin/rm -f "$archive"
}

run_uv() (
    # An inherited UV_* value must not change the catalog, mirror, architecture,
    # target installation, TLS verification, or Python selected by this script.
    for name in ${!UV_@} ${!PYTHON@}; do unset "$name"; done
    unset VIRTUAL_ENV CONDA_PREFIX CONDA_DEFAULT_ENV __PYVENV_LAUNCHER__
    export UV_PYTHON_INSTALL_DIR="$root/runtimes" UV_PYTHON_BIN_DIR="$generation/bin"
    export UV_CACHE_DIR="$root/cache" UV_NO_PROGRESS=1
    "$uv" --no-config --system-certs "$@"
)

save_file() {
    local target="$1" index=${#saved_paths[@]} existed
    if [[ -e "$target" ]]; then
        /bin/cp -pL "$target" "$snapshot/$index" || return 1
        existed=yes
    elif [[ -L "$target" ]]; then
        fail "Broken configuration symlink: $target"; return 1
    else
        existed=no
    fi
    printf '%s\t%s\n' "$existed" "$target" >> "$snapshot/files.tsv" || return 1
    saved_paths[$index]="$target"
    saved_exists[$index]="$existed"
}

check_runtime() {
    local actual
    python=$(run_uv python find "$request" --system --managed-python --no-project --no-python-downloads --resolve-links) || return 1
    actual=$("$python" -I -c 'import platform, ssl, sqlite3, venv; print(platform.python_version())') || return 1
    [[ "$actual" == "$version" ]] || { fail "Requested $version, executed $actual."; return 1; }
    if ! "$python" -I -m pip --version >/dev/null 2>&1; then "$python" -I -m ensurepip --upgrade || return 1; fi
    "$python" -I -m pip --version || return 1
    /bin/rm -rf "$generation/venv-check"
    "$python" -I -m venv "$generation/venv-check" || return 1
    actual=$("$generation/venv-check/bin/python" -I -c 'import platform; print(platform.python_version())') || return 1
    [[ "$actual" == "$version" ]] || return 1
    /bin/rm -rf "$generation/venv-check"
}

cleanup() {
    local status=$? i target
    trap - EXIT INT TERM
    if (( status != 0 )) && [[ "$transaction" == yes ]]; then
        printf 'Configuration failed; restoring the previous default and profiles.\n' >&2
        for ((i=${#saved_paths[@]}-1; i>=0; i--)); do
            target=${saved_paths[$i]}
            if [[ "${saved_exists[$i]}" == yes ]]; then
                /bin/cat "$snapshot/$i" > "$target" || printf 'RESTORE FAILED: %s\n' "$target" >&2
            else
                /bin/rm -f "$target" || printf 'RESTORE FAILED: %s\n' "$target" >&2
            fi
        done
        if [[ -n "$old_current" ]]; then
            /bin/ln -s "$old_current" "$root/.restore-$$"
            /bin/mv -fh "$root/.restore-$$" "$root/current" || printf 'RESTORE FAILED: current link\n' >&2
        else
            /bin/rm -f "$root/current"
        fi
        printf 'Recovery files: %s\n' "$snapshot" >&2
    fi
    if [[ "$locked" == yes ]]; then /bin/rm -f "$root/.lock/pid"; /bin/rmdir "$root/.lock"; fi
    exit "$status"
}

main() {
    set -euo pipefail
    local version='' isolated=no assume_yes=no arch request python actual profile quoted block zdot
    root="${HOME:?HOME must be set}/Library/Application Support/PythonSelector"
    local root_given=no
    while (( $# )); do
        case "$1" in
            --version|--root)
                (( $# >= 2 )) || { fail "Missing value for $1"; return 1; }
                if [[ "$1" == --version ]]; then version=$2; else root=$2; root_given=yes; fi
                shift 2 ;;
            --isolated) isolated=yes; shift ;;
            --yes) assume_yes=yes; shift ;;
            --help|-h)
                printf 'Usage: bash setup-python-mac.sh [--version X.Y.Z] [--yes]\n       --isolated --root /absolute/path: install and verify without editing profiles.\nDefault: 3.11.1. Supports Bash/Zsh on macOS. Restart terminals after installation.\n'
                return ;;
            *) fail "Unknown option: $1"; return 1 ;;
        esac
    done
    if [[ -z "$version" ]]; then
        if [[ "$assume_yes" == yes ]]; then version=3.11.1
        else
            printf 'Exact Python version to install [3.11.1]: '
            IFS= read -r version || { fail 'No input. Use --yes for the default or --version X.Y.Z.'; return 1; }
            version=${version:-3.11.1}
        fi
    fi
    validate_version "$version"
    [[ "$(/usr/bin/uname -s)" == Darwin ]] || { fail 'This script requires macOS.'; return 1; }
    [[ "$root" == /* && "$root" != / && "$root" != *:* && "$root" != *$'\n'* && "$root" != *$'\t'* ]] ||
        { fail 'Root must be an absolute non-root path without colons, tabs or newlines.'; return 1; }
    [[ "$isolated" != yes || "$root_given" == yes ]] || { fail '--isolated requires an explicit --root.'; return 1; }
    [[ "$isolated" == yes || $EUID != 0 ]] || { fail 'Run without sudo to configure your own account.'; return 1; }
    root=${root%/}
    # Use trusted macOS utilities even when a package manager supplied PATH.
    export PATH=/usr/bin:/bin:/usr/sbin:/sbin
    for name in ${!PYTHON@}; do unset "$name"; done
    unset VIRTUAL_ENV __PYVENV_LAUNCHER__
    /bin/mkdir -p "$root"
    [[ ! -e "$root/current" || -L "$root/current" ]] || { fail 'Refusing to replace an unmanaged current directory.'; return 1; }
    locked=no transaction=no old_current=''
    saved_paths=() saved_exists=()
    /bin/mkdir "$root/.lock" 2>/dev/null || { fail "Another run owns $root/.lock. If interrupted, check its pid before removing the lock."; return 1; }
    locked=yes
    printf '%s\n' "$$" > "$root/.lock/pid"
    trap cleanup EXIT
    trap 'exit 130' INT
    trap 'exit 143' TERM
    generation=$(/usr/bin/mktemp -d "$root/run.XXXXXXXX")
    snapshot="$generation/backup"
    /bin/mkdir -p "$snapshot" "$generation/bin"
    arch=$(/usr/bin/uname -m)
    if [[ "$arch" == arm64 ]] || [[ "$(/usr/sbin/sysctl -n hw.optional.arm64 2>/dev/null || :)" == 1 ]]; then arch=aarch64; fi
    download_uv "$arch"
    request="cpython-$version-macos-$arch-none"
    printf 'Installing/selecting CPython %s (%s)...\n' "$version" "$arch"
    run_uv python install "$request" --no-bin --no-registry
    if ! check_runtime; then
        printf 'Managed runtime did not pass complete verification; repairing it once...\n' >&2
        run_uv python install "$request" --no-bin --no-registry --reinstall
        check_runtime || { fail 'The repaired runtime still failed verification; defaults were not changed.'; return 1; }
    fi
    # Direct exec avoids CPython 3.11.1's venv/symlink prefix bug. The exact
    # patch directory also avoids uv's movable minor-version aliases.
    printf -v quoted '%q' "$python"
    for name in python python3 "python${version%.*}"; do
        printf '#!/bin/bash\nexec %s "$@"\n' "$quoted" > "$generation/bin/$name"
        /bin/chmod 755 "$generation/bin/$name"
    done
    for name in pip pip3; do
        printf '#!/bin/bash\nexec %s -m pip "$@"\n' "$quoted" > "$generation/bin/$name"
        /bin/chmod 755 "$generation/bin/$name"
    done
    # Commit only after the staged Python and its venv/pip pass.
    if [[ -L "$root/current" ]]; then old_current=$(/usr/bin/readlink "$root/current"); fi
    printf '%s\n' "$old_current" > "$snapshot/previous-current.txt"
    transaction=yes
    save_file "$root/activate.sh"
    make_activation "$root" "$root/activate.sh"
    /bin/ln -s "$generation" "$root/.current-$$"
    /bin/mv -fh "$root/.current-$$" "$root/current"
    if [[ "$isolated" != yes ]]; then
        zdot=${ZDOTDIR:-$HOME}
        [[ "$zdot" == /* ]] || { fail 'ZDOTDIR must be absolute.'; return 1; }
        printf -v quoted '%q' "$root/activate.sh"
        block="$generation/profile-block"
        printf '. %s\n' "$quoted" > "$block"
        # Do not create a higher-priority login file that would hide the user's
        # existing .bash_login or .profile.
        local bash_login="$HOME/.bash_profile"
        if [[ ! -e "$bash_login" ]]; then
            if [[ -e "$HOME/.bash_login" ]]; then bash_login="$HOME/.bash_login"
            elif [[ -e "$HOME/.profile" ]]; then bash_login="$HOME/.profile"; fi
        fi
        for profile in "$bash_login" "$HOME/.bashrc" \
                       "$zdot/.zprofile" "$zdot/.zshrc" "$zdot/.zlogin"; do
            save_file "$profile"
            write_profile "$profile" "$block"
        done
    fi
    . "$root/activate.sh"
    for name in python python3; do
        actual=$("$name" -c 'import platform; print(platform.python_version())')
        [[ "$actual" == "$version" ]] || { fail "$name resolves to $actual, expected $version."; return 1; }
        printf '%s -> %s (%s)\n' "$name" "$(command -v "$name")" "$actual"
    done
    pip --version
    pip3 --version
    transaction=no
    printf '\nVerified Python %s. Activation: %s/activate.sh\nBackups: %s\n' "$version" "$root" "$snapshot"
    if [[ "$isolated" == yes ]]; then printf 'Isolated mode: persistent shell configuration was not changed.\n'
    else printf 'Open a new terminal, or source the activation file above. Existing terminals/IDEs keep their prior environment.\n'; fi
}

if [[ "${BASH_SOURCE[0]}" == "$0" ]]; then main "$@"; fi
